### ISSUE TITLE
KeyError: 'token_type_ids'  in sentence pair classification for RoBERTa 

### ISSUE THREAD

**Issue by azizcu** [NadirEM/nlp-notebooks#2]
Fine_tune_ALBERT_sentence_pair_classification.ipynb
i use this code for sentence pair regression . For BERT & ALBERT it worked perfectly . But when i try RoBERTa , i got the error. Please have a look......

  0%|          | 0/86 [00:00<?, ?it/s]
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-68-895aa0126da3> in <module>()
     29 lr_scheduler = get_linear_schedule_with_warmup(optimizer=opti, num_warmup_steps=num_warmup_steps, num_training_steps=t_total)
     30 
---> 31 train_bert(net, criterion, opti, lr, lr_scheduler, train_loader, val_loader, epochs, iters_to_accumulate)

5 frames
/usr/local/lib/python3.6/dist-packages/torch/_utils.py in reraise(self)
    426             # have message field
    427             raise self.exc_type(message=msg)
--> 428         raise self.exc_type(msg)
    429 
    430 

KeyError: Caught KeyError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/worker.py", line 198, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "<ipython-input-62-86508170e099>", line 31, in __getitem__
    token_type_ids = encoded_pair['token_type_ids'].squeeze(0)  # binary tensor with "0" for the 1st sentence tokens & "1" for the 2nd sentence tokens
  File "/usr/local/lib/python3.6/dist-packages/transformers/tokenization_utils_base.py", line 204, in __getitem__
    return self.data[item]
KeyError: 'token_type_ids'

**Comment by Tom-Wangyoucai** [comment]
" dropout(): argument 'input' (position 1) must be Tensor, not str", how to deal it?

**Comment by ayushkothari27** [comment]
Were you able to solve this error? @azizcu
